version: "3.8"

services:
  # Laravel Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastkart-app
    restart: unless-stopped
    working_dir: /var/www/html/fastkart-laravel-api
    volumes:
      - ./:/var/www/html/fastkart-laravel-api
      - vendor_data:/var/www/html/fastkart-laravel-api/vendor
      - ./storage:/var/www/html/fastkart-laravel-api/storage
      - ./bootstrap/cache:/var/www/html/fastkart-laravel-api/bootstrap/cache
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_HOST=mysql
      - DB_DATABASE=fastkart
      - DB_USERNAME=root
      - DB_PASSWORD=FastKart_Ebstor_2024!
      - REDIS_HOST=redis
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=redis
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - fastkart-network

  # Nginx Web Server
  nginx:
    image: nginx:alpine
    container_name: fastkart-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./:/var/www/html/fastkart-laravel-api
      - ./docker/nginx/production.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - fastkart-network

  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: fastkart-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: FastKart_Ebstor_2024!
      MYSQL_DATABASE: fastkart
      MYSQL_USER: fastkart
      MYSQL_PASSWORD: FastKart_Ebstor_2024!
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "3307:3306"
    healthcheck:
      test:
        [
          "CMD",
          "mysqladmin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "root",
          "-pFastKart_Ebstor_2024!",
        ]
      timeout: 20s
      retries: 10
    networks:
      - fastkart-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: fastkart-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - fastkart-network

  # Queue Worker
  queue:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastkart-queue
    restart: unless-stopped
    working_dir: /var/www/html/fastkart-laravel-api
    volumes:
      - ./:/var/www/html/fastkart-laravel-api
      - vendor_data:/var/www/html/fastkart-laravel-api/vendor
    command: php artisan queue:work --sleep=3 --tries=3 --max-time=3600
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_HOST=mysql
      - DB_DATABASE=fastkart
      - DB_USERNAME=root
      - DB_PASSWORD=FastKart_Ebstor_2024!
      - REDIS_HOST=redis
      - QUEUE_CONNECTION=redis
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - fastkart-network

  # Scheduler (Cron)
  scheduler:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fastkart-scheduler
    restart: unless-stopped
    working_dir: /var/www/html/fastkart-laravel-api
    volumes:
      - ./:/var/www/html/fastkart-laravel-api
      - vendor_data:/var/www/html/fastkart-laravel-api/vendor
    command: >
      sh -c "while true; do
        php artisan schedule:run --verbose --no-interaction &
        sleep 60
      done"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_HOST=mysql
      - DB_DATABASE=fastkart
      - DB_USERNAME=root
      - DB_PASSWORD=FastKart_Ebstor_2024!
      - REDIS_HOST=redis
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - fastkart-network

  # phpMyAdmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: fastkart-phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: FastKart_Ebstor_2024!
    ports:
      - "8080:80"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - fastkart-network

volumes:
  mysql_data:
    driver: local
  redis_data:
    driver: local
  vendor_data:
    driver: local

networks:
  fastkart-network:
    driver: bridge
